### ISSUE TITLE
Add a 'Copy To Clipboard' button in code examples

### ISSUE THREAD

**Issue by ihsavru** [The-Code-Dose/thecodedose-website#4]
Add an icon on the top right corner so that when clicked it copy the code to your clipboard
<img width="819" alt="Screenshot 2023-08-19 at 1 21 48 AM" src="https://github.com/The-Code-Dose/thecodedose-website/assets/22816171/2bd9e50b-367e-4266-a624-19c6d58d55c1">

**Comment by rohitd99** [comment]
Hey @ihsavru can I get assigned to this issue?
